### ISSUE TITLE
Confused how it had to work

### ISSUE THREAD

**Issue by farcop** [flavio/kuberlr#95]
Already has binary kubectl1.29, but why it downloads 1.30 ?

![image](https://github.com/flavio/kuberlr/assets/3578167/738c9c9b-f6f6-4ebe-9948-b45ab2e04cf3)

```
bash-5.2$ kuberlr bins
system-wide kubectl binaries
+---+---------+----------------------+
| # | VERSION | BINARY               |
+---+---------+----------------------+
| 1 | 1.26.0  | /usr/bin/kubectl1.26 |
| 2 | 1.29.0  | /usr/bin/kubectl1.29 |
+---+---------+----------------------+


local kubectl binaries
No binaries found.
bash-5.2$ kubectl version
I0612 21:10:14.918858      38 versioner.go:87] Right kubectl missing, downloading version 1.30.2
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.30.2/bin/linux/arm64/kubectl
kubectl1.30.2 100% |████████████████████████████████████████| (50/50 MB, 8.5 MB/s) done.         
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by flavio** [comment]
It took me a while to figure it out... You've not set a kubernetes cluster to connect to. You can see that from this error message:

```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

That triggered an old behavior of kuberlr, which instead of using the latest version of the binary downloaded on the system it downloaded the latest version of kubectl published by upstream.

This has been changed with the recent versions of kuberlr.

I'm going to close this issue. Please, re-open it if this is still happening with the latest version of kuberlr.
